name: github action demo
run-name: ${{ github.actor }} is testing

permissions:
  pull-requests: write
  contents: write

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  testing-github-action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "trigger ${{ github.event_name }}"
      - run: echo "branch is ${{ github.ref }} of ${{ github.repository }}"
      
      - name: Checkout
        uses: actions/checkout@v4

      - run: echo "job status is ${{ job.status }}"  
        
      - name: Setup Java JDK
        uses: actions/setup-java@v4.6.0
        with:
          java-version: '21'
      
      - name: Setup Gradle
        uses: gradle/actions@v4.2.2

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}        
        
      - name: Run Tests
        run: ./gradlew test
        


  
                    
