name: github action demo
run-name: ${{ github.actor }} is testing

permissions:
  pull-requests: write
  contents: write

env:
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  testing-github-action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "trigger ${{ github.event_name }}"
      - run: echo "branch is ${{ github.ref }} of ${{ github.repository }}"
      
      - name: Checkout
        uses: actions/checkout@v4

      - run: echo "job status is ${{ job.status }}"  
        
      - name: Setup Java JDK
        uses: actions/setup-java@v4.6.0
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
 
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
 
      - name: Test with Gradle
        run: ./gradlew --info test
 
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }}
        with:
          files: build/test-results/**/*.xml
 
      - name: Cleanup Gradle Cache
        if: ${{ always() }}
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
